name: SMPL
favicon: null
layout_spectrum: 0.8847203741315752
typography_spectrum: 0.5078160909470171
title: SonicMuteProductionsLimited
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.10277049615979195
  lightness: 0.04575641732662916
  saturation: 0.8259515953250229
  rhythmicContrast: 0.7647508170921355
purpose: []
